app/estudiantes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name = 'estudiantes'),
    path('nuevo', views.crear),
    path('editar', views.modificar),
    path('baja', views.baja),
    path('eliminar', views.eliminar),
]

carrionJhon/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('estudiantes/', include('app.estudiantes.urls')),
    path('login/', include('app.login.urls')),
    path('', views.homePage, name='home_Page'),
]

app/estudiantes/models.py
from django.db import models

# Create your models here.

app/modelo/models.py
from django.db import models

# Create your models here.
class Estudiante(models.Model):

    listaGenero = (
        ('f', 'Femenino'),
        ('m', 'Masculino'),
    )
    listaEstadoCivil = (
        ('soltero', 'Solter@'),
        ('casado', 'Casad@'),
        ('viudo', 'Viud@'),
        ('divorciado', 'Divorciad@'),
        ('unionLibre', 'Unión Libre'),
    )

    estudiante_id = models.AutoField(primary_key=True)
    cedula = models.CharField(unique=True, max_length=10, null = False)
    matricula = models.PositiveIntegerField(unique=True, null = False)
    carrera = models.CharField(max_length=70, null = False)
    nombres = models.CharField(max_length=70, null = False)
    apellidos = models.CharField(max_length=70, null = False)
    genero = models.CharField(max_length=15, choices = listaGenero, null = False)
    estadoCivil = models.CharField(max_length=15, choices = listaEstadoCivil, null = False)
    fechaNacimiento = models.DateField(auto_now = False, auto_now_add = False, null = False)
    correo = models.EmailField(unique=True, max_length=100, null = False)
    telefono = models.CharField(max_length=15, null = False)
    celular = models.CharField(max_length=15, null = False)
    direccion = models.TextField(null = False)
    estado = models.BooleanField(null = False, default = True)

    def __str__(self):
        return self.cedula

app/estudiantes/forms.py
from django import forms
from app.modelo.models import Estudiante

class FormularioEstudiante(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = ["cedula", "matricula", "carrera", "nombres", "apellidos", "genero", "estadoCivil", "fechaNacimiento", "correo", "telefono", "celular", "direccion", "estado"]

app/estudiantes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .forms import FormularioEstudiante
from app.modelo.models import Estudiante
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def home(request):
    usuario = request.user
    print(usuario.get_all_permissions())
    if usuario.has_perm('modelo.view_estudiante'):
        listaEstudiantes = Estudiante.objects.all().order_by('apellidos')
        context = {
            'estudiantes': listaEstudiantes,
            'title': "Estudiantes",
            'mensaje': "Modulo Estudiantes"
        }
        return render(request, 'estudiante/home.html', context)
    else:
        messages.warning(request, 'No Permitido')
        return render(request, 'login/403.html')

@login_required
def crear(request):
    usuario = request.user
    if usuario.has_perm('modelo.add_estudiante'):
        formulario = FormularioEstudiante(request.POST)
        if request.method == 'POST':
            if formulario.is_valid():
                datos = formulario.cleaned_data
                estudiante = Estudiante()
                estudiante.cedula = datos.get('cedula')
                estudiante.matricula = datos.get('matricula')
                estudiante.carrera = datos.get('carrera')
                estudiante.nombres = datos.get('nombres')
                estudiante.apellidos = datos.get('apellidos')
                estudiante.genero = datos.get('genero')
                estudiante.estadoCivil = datos.get('estadoCivil')
                estudiante.fechaNacimiento = datos.get('fechaNacimiento')
                estudiante.correo = datos.get('correo')
                estudiante.telefono = datos.get('telefono')
                estudiante.celular = datos.get('celular')
                estudiante.direccion = datos.get('direccion')
                if datos.get('estado') == "on" :
                    estudiante.estado = True
                else:
                    estudiante.estado = False
                estudiante.save()
                messages.warning(request, 'Guardado Exitosamente')
                return redirect(home)
        context = {
            'f': formulario,
            'title': "Ingresar Estudiante",
            'mensaje': "Ingresar Nuevo Estudiante"
        }
        return render(request, 'estudiante/crear.html', context)
    else:
        messages.warning(request, 'No Permitido')
        return render(request, 'login/403.html')

@login_required
def modificar(request):
    usuario = request.user
    if usuario.has_perm('modelo.change_estudiante'):
        if request.GET['cedula']:
            dni = request.GET['cedula'];
            estudiante = Estudiante.objects.get(cedula=dni)
        else:
            if request.GET['matricula']:
                dni = request.GET['matricula'];
                estudiante = Estudiante.objects.get(matricula=dni)

        formulario = FormularioEstudiante(instance=estudiante)

        if request.method == 'POST':
            estudiante.cedula = request.POST['cedula']
            estudiante.matricula = request.POST['matricula']
            estudiante.carrera = request.POST['carrera']
            estudiante.apellidos = request.POST['apellidos']
            estudiante.nombres = request.POST['nombres']
            estudiante.genero = request.POST['genero']
            estudiante.estadoCivil = request.POST['estadoCivil']
            estudiante.fechaNacimiento = request.POST['fechaNacimiento']
            estudiante.correo = request.POST['correo']
            estudiante.telefono = request.POST['telefono']
            estudiante.celular = request.POST['celular']
            estudiante.direccion = request.POST['direccion']
            if 'estado' in request.POST:
                if request.POST['estado'] == "on":
                    estudiante.estado = True
                else:
                    estudiante.estado = False
            else:
                estudiante.estado = False
            estudiante.save()
            messages.warning(request, 'Datos Modificados')
            return redirect(home)
        context = {
            'f': formulario,
            'title': "Modificar Estudiantee",
            'mensaje': "Modificar datos de " + estudiante.nombres + " " + estudiante.apellidos
        }
        return render(request, 'estudiante/crear.html', context)
    else:
        messages.warning(request, 'No Permitido')
        return render(request, 'login/403.html')


@login_required
def baja(request):
    usuario = request.user
    if usuario.has_perm('modelo.delete_estudiante'):
        if request.GET['cedula']:
            dni = request.GET['cedula'];
            estudiante = Estudiante.objects.get(cedula=dni)
        else:
            if request.GET['matricula']:
                dni = request.GET['matricula'];
                estudiante = Estudiante.objects.get(matricula=dni)

        if estudiante:
            if estudiante.estado == True:
                estudiante.estado = False
                messages.warning(request, 'Estudiante Desactivado')
            else:
                estudiante.estado = True
                messages.warning(request, 'Estudiante Reactivado')
            estudiante.save()
            return redirect(home)
        else:
            messages.warning(request, 'Perdido')
            return redirect(home)
        return render(request, 'estudiante/crear.html', context)
    else:
        messages.warning(request, 'No Permitido')
        return render(request, 'login/403.html')


@login_required
def eliminar(request):
    usuario = request.user
    if usuario.has_perm('modelo.delete_estudiante'):
        if request.GET['cedula']:
            dni = request.GET['cedula'];
            estudiante = Estudiante.objects.get(cedula=dni)
        else:
            if request.GET['matricula']:
                dni = request.GET['matricula'];
                estudiante = Estudiante.objects.get(matricula=dni)

        if estudiante:
            if estudiante.delete():
                messages.warning(request, 'Estudiante Eliminado')
            else:
                messages.warning(request, 'No se pudo Eliminar')
            return redirect(home)
        else:
            messages.warning(request, 'Perdido')
            return redirect(home)
        return render(request, 'estudiante/crear.html', context)
    else:
        messages.warning(request, 'No Permitido')
        return render(request, 'login/403.html')

templates/estudiante/crear.html
{% extends "../index.html" %}

{% block body %}
<nav>
    <div class="nav-wrapper z-depth-2 purple lighten-2">
        <a href="#!" class="brand-logo">Estudiantes</a>
        <ul class="right hide-on-med-and-down">
            <li><a href="nuevo"><i class="material-icons left">playlist_add</i>Nuevo</a></li>
            <li><a href="/estudiantes/"><i class="material-icons left">keyboard_return</i>Regresar</a></li>
        </ul>
    </div>
</nav>
<div class="row">
    <div class="col s12">
        <div class="card z-depth-3">
            <form method="POST" action="">
                <div class="card-content">
                    <span class="card-title">{{mensaje}}</span>
                    <div class="row">
                        {% for field in f %}
                        <div id="campo_{{field.auto_id}}" class="input-field col s6">
                            {{field}}
                            <label for="{{field.auto_id}}">{{field.label_tag}}</label>
                        </div>
                        {% endfor %}
                        {% csrf_token %}
                    </div>
                </div>
                <div class="card-action">
                    <button type="submit" class="waves-effect waves-light btn blue"><i class="material-icons left">save</i> Guardar</button>
                    <a href="/estudiantes/" class="waves-effect waves-light btn red"><i class="material-icons left">cancel</i> Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}
{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, {});
        var chk = document.getElementById("campo_id_estado");
        chk.innerHTML = '<p><label><input type="checkbox" name="estado" id="id_estado" /><span>Estado</span></label></p>'
    });
</script>
{% endblock %}

templates/estudiante/home.html
{% extends "../index.html" %}

{% block body %}

<nav>
    <div class="nav-wrapper z-depth-2 purple lighten-2">
        <a href="#!" class="brand-logo">Estudiantes</a>
        <ul class="right hide-on-med-and-down">
            <li><a href="nuevo"><i class="material-icons left">playlist_add</i>Nuevo</a></li>
        </ul>
    </div>
</nav>
<div class="row">
    <div class="col s12">
        <div class="card z-depth-3">
            <div class="card-content">
                <span class="card-title">{{mensaje}}</span>
                <table class="highlight responsive-table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Cédula</th>
                            <th>Apellidos</th>
                            <th>Nombres</th>
                            <th>Genero</th>
                            <th>Estado</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in estudiantes %}
                        <tr>
                            <td>
                                <a href="editar?cedula={{item.cedula}}" title="Modificar"><i class="material-icons left">edit</i></a>
                                <a href="eliminar?cedula={{item.cedula}}" title="Eliminar"><i class="material-icons left">delete_sweep</i></a>
                                {% if item.estado == True %}
                                <a href="baja?cedula={{item.cedula}}" title="Dar de Baja"><i class="material-icons left">event_busy</i></a>
                                {% else %}
                                <a href="baja?cedula={{item.cedula}}" title="Dar de Baja"><i class="material-icons left">event_available</i></a>
                                {% endif %}

                            </td>
                            <td>{{item.cedula}}</td>
                            <td>{{item.apellidos}}</td>
                            <td>{{item.nombres}}</td>
                            {% if item.genero == 'm' %}
                            <td>Masculino</td>
                            {% else %}
                            <td>Femenino</td>
                            {% endif %}
                            {% if item.estado == True %}
                            <td><i class="material-icons left green-text">check_circle</i></td>
                            {% else %}
                            <td><i class="material-icons left red-text">cancel</i></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-action">

            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block js %}
<script>
    var eliminar = function(id){
        $.ajax({
            url: "eliminar",
            method: "POST",
            data: { id : id }
        }).success(function( msj ) {
            if(msj == "eliminado"){

            }
            if(msj == "no eliminado"){

            }
            if(msj == "perdido"){

            }
        });
    }
</script>
{% endblock %}